# Site settings
title: Yangls.nita|live your dream
description: >- # this means to ignore newlines until "baseurl:"
  Anyway,tomorrow is another day.
baseurl: ""  # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
repository:


pageview:
  provider: leancloud
  leancloud:
    app_id    : PrK32JwAxsVwQRgmh8ztNccp-gzGzoHsz
    app_key   : oL8p0Sy4TVt6rRcC5PnrP311
    app_class : Blog_Views

#Default Sources
sources:
  unpkg:
    leancloud_js_sdk: '//cdn1.lncld.net/static/js/3.4.1/av-min.js'
    jquery: 'https://unpkg.com/jquery@3.3.1/dist/jquery.min.js'


# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed


# Author Info
author:
  name     : Anita
  image    : https://i.postimg.cc/ncmy1sTN/QQ-20190525232528.jpg
  email    : yangls.nita@gmail.com
  github   : 
  twitter  : 
  linkedin : 
  facebook : 


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Posts default Permalink
permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock